# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftMilton' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  source 'https://github.com/App47/PodSpecs.git'
  source 'https://github.com/CocoaPods/Specs.git'

  # Pods for SwiftMilton
  pod 'MWFeedParser'
  pod 'EmbeddedAgent'

  target 'SwiftMiltonTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
